
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/serverdb?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: sp0stxx
  jpa:
     hibernate:
       ddl-auto: create
       properties:
         hibernate:
           dialect: org.hibernate.dialect.MySQL8Dialect
           format_sql: true
       show-sql: true