spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/movietopia?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: "${dbPass}"
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

carousel:
  images: avatar3.jpg, avengers.jpg, darkknight.jpg, deadpool.jpg, sw-fa.jpg
  refresh-cron: "0 */5 * * * *"

#cloudinary:
#  api-key:
#    api-secret:
#      cloud-name:
